import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np
import pytest
from bib2.cerebellum.forward_model import CerebellumEngine

def test_cerebellar_simple_and_complex_spikes():
    cb = CerebellumEngine(n_granule=256, n_purkinje=64, n_deep=16)
    mossy_input = np.random.uniform(0, 1, 64).astype(np.float32)
    # Simple spikes generated by parallel fibers
    simple_spikes = cb.cortex.step_simple_spikes(mossy_input)
    assert simple_spikes.shape == (64,)
    assert np.all(simple_spikes >= 0.0)

def test_climbing_fiber_ltd_plasticity():
    cb = CerebellumEngine(n_granule=256, n_purkinje=64, n_deep=16)
    mossy_input = np.ones(64, dtype=np.float32)
    initial_weights = cb.cortex.weights_parallel_purkinje.copy()
    
    # Fire climbing fiber error spikes alongside parallel spikes
    error_spikes = np.ones(64, dtype=np.float32) * 0.9
    cb.cortex.apply_climbing_ltd(mossy_input, error_spikes, lr=0.05)
    
    # Synaptic weights must decrease (AMPA internalization / LTD)
    assert np.mean(cb.cortex.weights_parallel_purkinje) < np.mean(initial_weights)

def test_forward_model_prediction_and_correction():
    cb = CerebellumEngine(n_granule=256, n_purkinje=64, n_deep=16)
    intended_command = np.array([0.5, 0.2, -0.1, 0.8] * 16, dtype=np.float32)
    sensory_state = np.zeros(64, dtype=np.float32)
    predicted_state, micro_correction = cb.step(intended_command, sensory_state)
    assert predicted_state.shape == (64,)
    assert micro_correction.shape == (64,)

def test_deep_cerebellar_nuclei_disinhibition():
    cb = CerebellumEngine(n_granule=256, n_purkinje=64, n_deep=16)
    # High Purkinje firing strongly inhibits deep nuclei
    high_purkinje = np.ones(64, dtype=np.float32) * 0.9
    out_inhibited = cb.deep_nuclei.step(high_purkinje)
    
    # Low Purkinje firing disinhibits deep nuclei
    low_purkinje = np.ones(64, dtype=np.float32) * 0.1
    out_disinhibited = cb.deep_nuclei.step(low_purkinje)
    
    assert np.mean(out_disinhibited) > np.mean(out_inhibited)
